name: CI/CD Ruby Importer

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: gem install sqlite3 minitest

      - name: Run Minitest
        run: ruby importer/tests/test_importer.rb

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image with version tag
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ruby-importer:${{ steps.get_version.outputs.version }} ./importer
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ruby-importer:${{ steps.get_version.outputs.version }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/ruby-importer:latest

      - name: Push Docker image (version + latest)
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ruby-importer:${{ steps.get_version.outputs.version }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ruby-importer:latest

  update-release:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Nécessaire pour voir l’historique complet des tags

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | grep -B1 "${GITHUB_REF#refs/tags/}" | head -n1)
          echo "Comparing to previous tag: $PREV_TAG"
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          git log "$PREV_TAG..${GITHUB_REF#refs/tags/}" --pretty=format:"- %s (%an)" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Update GitHub release description
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body: |
            Docker image published:

            ```
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ruby-importer:${{ github.ref_name }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ruby-importer:latest
            ```

            Changes since last release:
            ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
